apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-blue
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-monitoring
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-monitoring
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-monitoring
spec:
  destination:
    namespace: bgd-blue
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/Pacificdubey/ArgoCD
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
